### ISSUE TITLE
hi i have problem when go to admin endpoints 

### ISSUE THREAD

**Issue by shadihh9** [blabla1337/skf-labs#106]
hi i have problem when go to admin endpoints  in graphql-injections when  go  to admin  endpoints   it logout and ask me username and pass

**Comment by blabla1337** [comment]
@david3107 Can you maybe have some feedback to what to expect and to do?
Also @shadihh9 the writeup is also not explaining it?

**Comment by tsluyter** [comment]
Please go ahead and close this issue @blabla1337 . They are not coming back.

**Comment by tsluyter** [comment]
@shadihh9 or @blabla1337 please close this issue.
