### ISSUE TITLE
Wrong amount of hints in XSS Labs

### ISSUE THREAD

**Issue by Bergiu** [blabla1337/skf-labs#111]
https://github.com/blabla1337/skf-labs/blob/98c6426c54d3d00d0bbc3fce518c5c70beb98996/XSS-url/templates/index.html#L48

There are 0/3 hints shown, but when i try to open the hints, i can only open 2 hints, because there are only 2 list elements (in line 53-58). Is there missing a third list element, or should there just be 2 hints?

The problem also ocures in the following files:
https://github.com/blabla1337/skf-labs/blob/98c6426c54d3d00d0bbc3fce518c5c70beb98996/XSS-attribute/templates/index.html
https://github.com/blabla1337/skf-labs/blob/98c6426c54d3d00d0bbc3fce518c5c70beb98996/XSS-DOM/templates/index.html
https://github.com/blabla1337/skf-labs/blob/e8a833b4b56ae02a87957b40999e998f33dd4eb1/XSS/templates/index.html
https://github.com/blabla1337/skf-labs/blob/98c6426c54d3d00d0bbc3fce518c5c70beb98996/XSS-DOM-2/templates/index.html

**Comment by blabla1337** [comment]
Thanks for letting us know, I have updated the labs and im now pushing the new Labs to the docker! +1
