### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by leixyou** [blabla1337/skf-labs#113]
https://github.com/blabla1337/skf-labs/blob/4a1b996e9ed80ad5b9d47016a8ec6dc0a39f1589/Auth-bypass-2/Docker/Dockerfile#L10

WORKDIR /skf-labs/DES-Pickle-2 => WORKDIR /skf-labs/Auth-bypass-2

**Comment by blabla1337** [comment]
Thank you for letting us now! We have updated the lab and im pushing it now to the Docker hub
