### ISSUE TITLE
Contribution.

### ISSUE THREAD

**Issue by Tikam02** [blabla1337/skf-labs#12]
@blabla1337 I have Experience on Various attack vectors and OWASP-Top 10 model attacks. Also, I do CTFs and Pentesting, so can I contribute to SKF-Labs.

**Comment by blabla1337** [comment]
That would be really great if you can add more lab challenges 😊

**Comment by giuliocomi** [comment]
we may add a kind of roadmap to keep track of the challenges to add as well :)

**Comment by blabla1337** [comment]
Yes good point, can you add a list on the readme of the things you and the guys are already working on?

**Comment by giuliocomi** [comment]
Hello @Tikam02 , we have now a roadmap of the challenges to add in skf labs. If you want to contribute, please see https://github.com/blabla1337/skf-labs/blob/master/README.md to implement the TODO challs or propose new ones. Keep in mind that the template should be compatible with the one currently in use. Also note that the tests are meant for educational purpose, so let's avoid tricky stuff :-).
