### ISSUE TITLE
Containerized apps run as root

### ISSUE THREAD

**Issue by tsluyter** [blabla1337/skf-labs#120]
It is inherently risky to run containerized applications as root, as is outlined in many "container escape" documents.

Yes, in many cases the container will need to run in "privileged" mode, but we cannot guarantee that students will never do this. So, it's better to protect students against themselves! Let's consider refactoring our lab containers to run as non-root user. Let's lead by example! :)

**Comment by PunitTailor55** [comment]
Hey could you possibly tell me how to run docker with user permission who has only read and execute access.

**Comment by tsluyter** [comment]
@PunitTailor55 do you mean Docker itself, or do you mean the software inside the containers? 

If it's the prior: on Windows and MacOS this is easy and Docker Desktop takes care of it all in one go. No local admin rights needed at all. On Linux it'll require more doing.

If it's the latter: the branch I linked to has an example.

**Comment by PunitTailor55** [comment]
I am talking about Docker. Docker shell default run as root. How can I give
normal user permissions? Such as read and execute only.
Punit Darji.
+91-9601159402

**Comment by tsluyter** [comment]
A) That question is really not relevant to this issue, nor to this project.

B) You can research this by searching for "docker non-root" on the web. There are ways of doing what you want (using the "_docker_" group), but [some sources suggest](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo) this is (very) dangerous.

**Comment by tsluyter** [comment]
I see that you are addressing all these through your own branches. 

Once they're all fixed, could you close this issue?

**Comment by PunitTailor55** [comment]
Sure, I will do that.

**Comment by PunitTailor55** [comment]
Please closed the issue.
