### ISSUE TITLE
SKF Labs not listed at OWASP vulnerable webapps

### ISSUE THREAD

**Issue by tsluyter** [blabla1337/skf-labs#121]
OWASP maintains lists of vulnerable webapps to play and learn with. Despite being (at least somewhat) related to OWASP, they don't list the SKF labs. We might consider submitting a request to get listed. 

-> https://owasp.org/www-project-vulnerable-web-applications-directory/

**Comment by blabla1337** [comment]
Thanks I have updated the OWASP page and we are now listed there :)

**Comment by tsluyter** [comment]
Nice, I see it! We're on here -> https://owasp.org/www-project-vulnerable-web-applications-directory/

Thanks for that!
