### ISSUE TITLE
File injection lab has issues

### ISSUE THREAD

**Issue by sudhikshahg** [blabla1337/skf-labs#126]
When I run File injection in web portal or on docker I get below error could you help me with resolving the same

builtins.OSError
OSError: No content, file name. Nothing is given
![image](https://user-images.githubusercontent.com/60124430/106096605-e3669080-615b-11eb-861a-290eadc32995.png)

**Comment by tsluyter** [comment]
I am unfamiliar with the "web portal" you're referring to. We can of course hlep you troubleshoot the issue you're having with the Docker container.

If your problem persists, please describe your exact steps to reproducing this problem. 

If the issue no longer persists, please close this issue record.

**Comment by sudhikshahg** [comment]
When I meant portal it was at this location https://demo.securityknowledgeframework.org/dashboard but nevertheless I was able to resolve same by installing pyexcel-xls package on local machine hence closing the issue.
