### ISSUE TITLE
Unable to download the docker file

### ISSUE THREAD

**Issue by 007divyachawla** [blabla1337/skf-labs#53]
Error response from daemon: manifest for blabla1337/owasp-skf-lab:graphql-IDOR not found

**Comment by mzfr** [comment]
@007divyachawla Can you please explain the issue? What command did you run from which directory?

**Comment by 007divyachawla** [comment]
@mzfr I run the following command which is mention in the https://owasp-skf.gitbook.io/asvs-write-ups/kbid-285-graphql-idor

Command is $ sudo docker pull blabla1337/owasp-skf-lab:graphql-IDOR

**Comment by mzfr** [comment]
Yeah so it looks like Dockerhub isn't updated with that tag because I can't find any `graphql-idor` [there](https://hub.docker.com/r/blabla1337/owasp-skf-lab/tags)

I think @blabla1337 would have to update it in order to get it there.

**Comment by 007divyachawla** [comment]
Can you please update the same.

**Comment by mzfr** [comment]
I don't have the permission to do so, but if you want that challenge then you can download that from the GitHub repository and then build the docker.

**Comment by blabla1337** [comment]
Hi Guys,

I merged the pull request and also applied a fix for the DB error, it's now working again.
Also pushed the docker lab to the hub:
docker run -ti -p 127.0.0.1:5000:5000 blabla1337/owasp-skf-lab:graphql-idor

Thanks for the heads up and help.

Kind regards,
Glenn
